export const tools = [
  { slug: "lottery", name: "隨機抽名單", description: "貼上名單，用安全隨機來源抽出一位或多位成員。", symbol: "✦", accent: "blue", status: "READY" },
  { slug: "background-remover", name: "圖片去背", description: "在瀏覽器本機免費移除背景，或切換 remove.bg API 取得更高畫質，下載透明 PNG。", symbol: "◐", accent: "coral", status: "READY" },
  { slug: "ai-flowchart", name: "流程圖", description: "用中文描述流程，自動驗證並匯出 Mermaid、PNG、SVG 與 draw.io。", symbol: "⌘", accent: "mint", status: "BETA" },
  { slug: "gantt", name: "甘特圖", description: "拖曳排出專案時程：群組、里程碑與依賴關係，匯出 PNG、CSV、Mermaid 與 JSON。", symbol: "▤", accent: "fuji", status: "BETA" },
  { slug: "random-groups", name: "隨機分組", description: "貼上名單，公平隨機分成小組：可指定組數或每組人數，結果可複製或下載 CSV。", symbol: "⁘", accent: "toki", status: "READY" },
  { slug: "image-compressor", name: "圖片壓縮", description: "本機批次壓縮與轉檔：JPG、PNG、WebP，可調品質與尺寸，圖片不上傳。", symbol: "◱", accent: "sora", status: "READY" },
  { slug: "qr-code", name: "QR Code 產生器", description: "即時產生 QR Code，自訂顏色與容錯等級，下載 PNG、SVG 或直接複製。", symbol: "▦", accent: "sumi", status: "READY" },
  { slug: "countdown-timer", name: "倒數計時器", description: "活動與簡報用的全螢幕倒數：快速預設、警示變色、結束提示音。", symbol: "◷", accent: "matsuba", status: "READY" },
  { slug: "pdf-toolkit", name: "PDF 合併與取頁", description: "在瀏覽器本機合併多份 PDF、取出指定頁面，檔案不上傳。", symbol: "⧉", accent: "fuji", status: "BETA" },
  { slug: "text-cleaner", name: "文字清理", description: "去空白、去重複行、排序與全形轉半形，即時統計字數，內容不上傳。", symbol: "¶", accent: "mint", status: "READY" },
  { slug: "exif-cleaner", name: "照片隱私清除", description: "無損移除 EXIF、GPS 位置與拍攝資訊，畫質不變，照片不上傳。", symbol: "◉", accent: "coral", status: "READY" },
  { slug: "chinese-converter", name: "繁簡轉換", description: "OpenCC 繁簡互轉，支援台灣用詞（軟件→軟體），本機處理不上傳。", symbol: "繁", accent: "blue", status: "READY" },
  { slug: "password-generator", name: "密碼產生器", description: "Web Crypto 安全隨機產生高強度密碼，可調長度與字元類別，不上傳不儲存。", symbol: "⁂", accent: "sumi", status: "READY" },
  { slug: "favicon-generator", name: "Favicon 產生器", description: "用文字、emoji 或圖片產生整套 favicon，附 HTML 與 manifest 片段。", symbol: "◆", accent: "sora", status: "READY" },
] as const;
